# Numpy Project :- Student Result Analysis

##### **Description About Data**
There is a 'students_marks.csv' file which contains data of 100 students.
There are 100 rows where every row representing a student data. 
There are four columns where first column contains roll number and 
next three columns contains marks of maths, physics and chemistry.

**Importing the numpy library**

In [1]:
import numpy as np

**Read the data from csv file into numpy array**

In [5]:
students_data=np.loadtxt('students_marks.csv',delimiter=',')

**Find the shape of data**

In [6]:
students_data.shape
(100,4)

(100, 4)

**Display first 5 rows of data**

In [7]:
print(students_data[:5])

[[101.  81.  75.  68.]
 [102.  42.  55.  49.]
 [103.  90.  88.  92.]
 [104.  67.  71.  65.]
 [105.  33.  40.  37.]]


**Find the total of marks of each student**

In [8]:
print(students_data[:,1:].sum(axis=1))
                         

[224. 146. 270. 203. 110. 239. 178. 283. 215. 263. 148. 193. 240. 297.
 124. 219. 171. 275. 207. 245. 140. 207. 286. 185. 253. 118. 227. 270.
 162. 245. 207. 131. 279. 233. 158. 258. 198. 292. 130. 231. 269. 179.
 208. 273. 111. 247. 188. 219. 287. 152. 238. 204. 167. 268. 127. 239.
 259. 143. 211. 280. 183. 244. 193. 294. 120. 224. 262. 161. 205. 270.
 130. 250. 200. 232. 286. 149. 241. 214. 173. 277. 115. 225. 267. 155.
 256. 192. 217. 292. 164. 235. 203. 274. 140. 262. 214. 176. 283. 124.
 247. 208.]


**Add a new column that will store the total of marks of each student**

In [9]:
total_marks=students_data[:,1:].sum(axis=1)
print(total_marks)

[224. 146. 270. 203. 110. 239. 178. 283. 215. 263. 148. 193. 240. 297.
 124. 219. 171. 275. 207. 245. 140. 207. 286. 185. 253. 118. 227. 270.
 162. 245. 207. 131. 279. 233. 158. 258. 198. 292. 130. 231. 269. 179.
 208. 273. 111. 247. 188. 219. 287. 152. 238. 204. 167. 268. 127. 239.
 259. 143. 211. 280. 183. 244. 193. 294. 120. 224. 262. 161. 205. 270.
 130. 250. 200. 232. 286. 149. 241. 214. 173. 277. 115. 225. 267. 155.
 256. 192. 217. 292. 164. 235. 203. 274. 140. 262. 214. 176. 283. 124.
 247. 208.]


In [10]:
total_marks=total_marks.reshape(-1,1)
print(total_marks[:5])

[[224.]
 [146.]
 [270.]
 [203.]
 [110.]]


**Display first 5 rows of data with newly added column for total of marks**

In [11]:
students_data=np.concatenate((students_data,total_marks),axis=1) #Broadcasting
students_data[:5]

array([[101.,  81.,  75.,  68., 224.],
       [102.,  42.,  55.,  49., 146.],
       [103.,  90.,  88.,  92., 270.],
       [104.,  67.,  71.,  65., 203.],
       [105.,  33.,  40.,  37., 110.]])

**Display last 5 rows of data with newly added column for total of marks**

In [12]:
students_data[-5:]

array([[196.,  56.,  62.,  58., 176.],
       [197.,  96.,  92.,  95., 283.],
       [198.,  38.,  45.,  41., 124.],
       [199.,  84.,  80.,  83., 247.],
       [200.,  71.,  67.,  70., 208.]])

**Find the average of marks of each student**

In [13]:
average_marks=(students_data[:,-1]/3).round(2)
print(average_marks)

[74.67 48.67 90.   67.67 36.67 79.67 59.33 94.33 71.67 87.67 49.33 64.33
 80.   99.   41.33 73.   57.   91.67 69.   81.67 46.67 69.   95.33 61.67
 84.33 39.33 75.67 90.   54.   81.67 69.   43.67 93.   77.67 52.67 86.
 66.   97.33 43.33 77.   89.67 59.67 69.33 91.   37.   82.33 62.67 73.
 95.67 50.67 79.33 68.   55.67 89.33 42.33 79.67 86.33 47.67 70.33 93.33
 61.   81.33 64.33 98.   40.   74.67 87.33 53.67 68.33 90.   43.33 83.33
 66.67 77.33 95.33 49.67 80.33 71.33 57.67 92.33 38.33 75.   89.   51.67
 85.33 64.   72.33 97.33 54.67 78.33 67.67 91.33 46.67 87.33 71.33 58.67
 94.33 41.33 82.33 69.33]


**Add a new column that will store the average of marks of each student**

In [14]:
average_marks=average_marks.reshape(-1,1)
students_data=np.concatenate((students_data,average_marks),axis=1)

**Display first 5 rows of data with newly added column for average of marks**

In [15]:
print(students_data[:5])

[[101.    81.    75.    68.   224.    74.67]
 [102.    42.    55.    49.   146.    48.67]
 [103.    90.    88.    92.   270.    90.  ]
 [104.    67.    71.    65.   203.    67.67]
 [105.    33.    40.    37.   110.    36.67]]


**Display first 5 rows of data with newly added column for average of marks**

In [16]:
print(students_data[-5:])

[[196.    56.    62.    58.   176.    58.67]
 [197.    96.    92.    95.   283.    94.33]
 [198.    38.    45.    41.   124.    41.33]
 [199.    84.    80.    83.   247.    82.33]
 [200.    71.    67.    70.   208.    69.33]]


**Find the average of marks of maths subject**

In [17]:
average_marks_math = students_data[:, 1].mean().round(2)
print(f"Average of marks of maths subject:{average_marks_math}")

Average of marks of maths subject:70.42


**Find the average of marks of physics subject**

In [15]:
average_marks_physics = students_data[:, 2].mean().round(2)
print(f"Average of marks of Physics subject:{average_marks_physics}")

Average of marks of Physics subject:71.42


**Find the average of marks of chemistry subject**

In [16]:
average_marks_chemistry = students_data[:, 3].mean().round(2)
print(f"Average of marks of Chemistry subject:{average_marks_chemistry}")

Average of marks of Chemistry subject:71.02


**Find the highest marks in maths subject**

In [17]:
highest_mark_math = round(students_data[:, 1].max())
print(f"Highest marks in maths subject:{highest_mark_math}")

Highest marks in maths subject:99


**Find the highest marks in physics subject**

In [18]:
highest_mark_physics = round(students_data[:, 2].max())
print(f"Highest marks in Physics subject:{highest_mark_physics}")

Highest marks in Physics subject:100


**Find the highest marks in chemistry subject**

In [19]:
highest_mark_chemistry = round(students_data[:, 3].max())
print(f"Highest marks in Chemistry subject:{highest_mark_chemistry}")

Highest marks in Chemistry subject:99


**Find the lowest marks in maths subject**

In [20]:
lowest_mark_math = round(students_data[:, 1].min())
print(f"Lowest marks in Maths subject:{lowest_mark_math }")

Lowest marks in Maths subject:33


**Find the lowest marks in physics subject**

In [21]:
lowest_mark_physics = round(students_data[:, 2].min())
print(f"Lowest marks in Physics subject:{lowest_mark_physics}")

Lowest marks in Physics subject:40


**Find the lowest marks in chemistry subject**

In [22]:
lowest_mark_chemistry = round(students_data[:, 3].min())
print(f"Lowest marks in Chemistry subject:{lowest_mark_chemistry}")

Lowest marks in Chemistry subject:36


**Count the number of students who have scored more than or equal to 90 marks in maths subject**

In [23]:
Student_count=(students_data[:, 1]>=90).sum()
print(f"Student scored >=90 in Maths:{Student_count}")

Student scored >=90 in Maths:20


**Count the number of students who have scored more than or equal to 90 marks in physics subject**

In [24]:
Student_count=(students_data[:, 2]>=90).sum()
print(f"Student scored >=90 in Physics:{Student_count}")

Student scored >=90 in Physics:13


**Count the number of students who have scored more than or equal to 90 marks in Chemistry subject**

In [25]:
Student_count=(students_data[:, 3]>=90).sum()
print(f"Student scored >=90 in Chemistry:{Student_count}")

Student scored >=90 in Chemistry:20


**Count the number of students who have scored average marks more than or equal to 60**

In [26]:
Student_count=(average_marks>=60).sum()
print(f"Number of Student Average Marks >=60: {Student_count}")

Number of Student Average Marks >=60: 71


**Count the number of students who have scored average marks less than 50**

In [27]:
print(f'''Number of students who have scored average marks less than 50 :
{(average_marks<50).sum()}''')

Number of students who have scored average marks less than 50 :
17


**Count the number of students who have scored average marks between 80 and 90**

In [28]:
print(f'''Number of students who have scored average marks >80 and<90  :
{((average_marks>=80) & (average_marks<=90)).sum()}''')

Number of students who have scored average marks >80 and<90  :
21


**Count the number of students who have scored marks more than or equal to 90 in all subjects**

In [89]:
print(f'''Number of students who have scored  marks >=90 in all subject  :
{((students_data[:,1] >= 90) & 
                 (students_data[:,2] >= 90) & 
                 (students_data[:,3] >= 90)).sum()
}''')

Number of students who have scored  marks >=90 in all subject  :
12


**Count the number of students who have scored marks more than or equal to 90 in any subject**

In [91]:
print(f'''Number of students who have scored marks >=90 in any subject :
{((students_data[:,1] >= 90) | 
                 (students_data[:,2] >= 90) | 
                 (students_data[:,3] >= 90)).sum()
}''')

Number of students who have scored marks >=90 in any subject :
22


**Save the Students Result Analysis Data to new 'students_result.csv' file**

In [19]:
np.savetxt(
    "students_result.csv",
    students_data,
    delimiter=",",
    header="Roll_Number,Math,Physics,Chemistry,Total_Marks,Average_Marks",
    fmt="%d,%d,%d,%d,%d,%.2f",
    comments=""
)
print("Data saved to students_result.csv")




Data saved to students_result.csv
